name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask

    - name: Executar testes
      run: python -m pytest